name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Executando deploy automático no servidor local
        run: |
          cd ~/projeto-impulso-jovem
          git pull origin main
          docker compose --profile full up -d --build
          docker exec ij-api npx prisma db push
